#!/usr/bin/env bash
set -euo pipefail

PROJECT_ID="${PROJECT_ID:-visma-274514}"
REGION="${REGION:-europe-north1}"
JOB="${JOB:-printward-freight-sync-demo}"
SERVICE_ACCOUNT="${SERVICE_ACCOUNT:-webshop-api@visma-274514.iam.gserviceaccount.com}"
VPC_CONNECTOR="${VPC_CONNECTOR:-connector-cloudrun-sql}"

GCS_BUCKET="${GCS_BUCKET:-pdf-service-bucket}"
GCS_PREFIX="${GCS_PREFIX:-9992/}"
NSHIFT_OUTPUT_GCS_BUCKET="${NSHIFT_OUTPUT_GCS_BUCKET:-pdf-service-bucket}"
NSHIFT_OUTPUT_GCS_PREFIX="${NSHIFT_OUTPUT_GCS_PREFIX:-freight/9992/}"

SQLSERVER_HOST="${SQLSERVER_HOST:-10.61.16.34}"
SQLSERVER_DATABASE="${SQLSERVER_DATABASE:-F9992}"
NSHIFT_FETCH_ENABLED="${NSHIFT_FETCH_ENABLED:-false}"
NSHIFT_SYNC_DRY_RUN="${NSHIFT_SYNC_DRY_RUN:-true}"
NSHIFT_SYNC_LIMIT="${NSHIFT_SYNC_LIMIT:-1}"
NSHIFT_ALLOWED_ORDER_NUMBERS="${NSHIFT_ALLOWED_ORDER_NUMBERS:-}"
NSHIFT_ALLOWED_CONSIGNMENT_NUMBERS="${NSHIFT_ALLOWED_CONSIGNMENT_NUMBERS:-}"

ENV_VARS="^@^GCS_BUCKET=${GCS_BUCKET}@GCS_PREFIX=${GCS_PREFIX}@SQLSERVER_HOST=${SQLSERVER_HOST}@SQLSERVER_PORT=1433@SQLSERVER_DATABASE=${SQLSERVER_DATABASE}@NSHIFT_OUTPUT_GCS_BUCKET=${NSHIFT_OUTPUT_GCS_BUCKET}@NSHIFT_OUTPUT_GCS_PREFIX=${NSHIFT_OUTPUT_GCS_PREFIX}@NSHIFT_PRINT_OPERATION=printWaybill@NSHIFT_BOOKED_STATUSES=2,8@NSHIFT_SYNC_LOOKBACK_DAYS=3@NSHIFT_SYNC_LOOKAHEAD_DAYS=14@NSHIFT_FETCH_ENABLED=${NSHIFT_FETCH_ENABLED}@NSHIFT_SYNC_DRY_RUN=${NSHIFT_SYNC_DRY_RUN}@NSHIFT_SYNC_LIMIT=${NSHIFT_SYNC_LIMIT}@NSHIFT_ALLOWED_ORDER_NUMBERS=${NSHIFT_ALLOWED_ORDER_NUMBERS}@NSHIFT_ALLOWED_CONSIGNMENT_NUMBERS=${NSHIFT_ALLOWED_CONSIGNMENT_NUMBERS}"
SECRET_VARS="SQLSERVER_USER=SQL_UID:latest,SQLSERVER_PASSWORD=SQL_PWD:latest"
if [[ "${NSHIFT_FETCH_ENABLED}" == "true" ]]; then
  SECRET_VARS="${SECRET_VARS},NSHIFT_USERNAME=NSHIFT_USERNAME:latest,NSHIFT_GROUP_NAME=NSHIFT_GROUP_NAME:latest,NSHIFT_PASSWORD=NSHIFT_PASSWORD:latest"
fi

gcloud run jobs deploy "${JOB}" \
  --project "${PROJECT_ID}" \
  --region "${REGION}" \
  --source . \
  --service-account "${SERVICE_ACCOUNT}" \
  --vpc-connector "${VPC_CONNECTOR}" \
  --vpc-egress private-ranges-only \
  --tasks 1 \
  --max-retries 0 \
  --task-timeout 15m \
  --command node \
  --args src/freight-sync-job.js \
  --set-env-vars "${ENV_VARS}" \
  --set-secrets "${SECRET_VARS}"
